#! /usr/bin/env python

import os
import sys
from dateutil import parser


BACK_LOG_SIZE = 14

if len(sys.argv) > 1:
	print "This script deletes all but the " + str(BACK_LOG_SIZE) +" newest logs generated by the uploader." 
	print "It prints this message when run with any parameters. None are required."
	sys.exit()

strdates = []
for root, dirs, files in os.walk("logfiles/"):
	if len(files) > BACK_LOG_SIZE:
		for filename in files:
			if len(filename) > 8:
				filename = filename.strip()
				strDate = filename[:-8]
				strDate = strDate.replace("_", " ")
				strdates.append(strDate)

#sorts the array to reverse rder (i.e. newest first)
strdates.sort( key=parser.parse, reverse=True)
i = -1
for date in strdates:
	i = i + 1
	if i < BACK_LOG_SIZE : #skips the newest 10
		continue
	else:
		#have to parse the filename back into shape
		filename = date.replace(" ", "_")
		filename = "logfiles/" + filename + "_log.log"
		print filename
		os.remove(filename)
